{ config, lib, ... }:

let
  cfg = config.xj.publicDotfiles;
  repoPath = path: config.lib.file.mkOutOfStoreSymlink "${cfg.repoRoot}/${path}";
in
{
  config = lib.mkIf cfg.enable {
    home.file = {
      ".amethyst.yml".source = repoPath ".config/amethyst/amethyst.yml";
      ".tmux.conf".text = ''
        # Generated by Home Manager from public-dotfiles. Do not edit.
        source-file ~/.config/tmux/tmux.conf
      '';
      ".zprofile".source = repoPath ".zprofile";
      ".zshrc".source = repoPath ".zshrc";
    };

    xdg.configFile = {
      "bat" = {
        source = ../../.config/bat;
        force = true;
      };
      "amethyst" = {
        source = repoPath ".config/amethyst";
        force = true;
      };
      "karabiner" = {
        source = repoPath ".config/karabiner";
        force = true;
      };
      "lazygit" = {
        source = ../../.config/lazygit;
        force = true;
      };
      "nvim" = {
        source = repoPath ".config/nvim";
        force = true;
      };
      "opencode" = {
        source = repoPath ".config/opencode";
        force = true;
      };
      "starship.toml".source = ../../.config/starship.toml;
      "yazi" = {
        source = ../../.config/yazi;
        force = true;
      };
    };
  };
}
