{ config, lib, ... }:

let
  cfg = config.xj.publicDotfiles;
in
{
  config = lib.mkIf cfg.enable {
    home.file = {
      ".amethyst.yml".source = ../../.config/amethyst/amethyst.yml;
      ".tmux.conf".text = ''
        # Generated by Home Manager from public-dotfiles. Do not edit.
        source-file ~/.config/tmux/tmux.conf
      '';
      ".zprofile".source = ../../.zprofile;
      ".zshrc".source = ../../.zshrc;
    };

    xdg.configFile = {
      "bat" = {
        source = ../../.config/bat;
        force = true;
      };
      "amethyst" = {
        source = ../../.config/amethyst;
        force = true;
      };
      "karabiner" = {
        source = ../../.config/karabiner;
        force = true;
      };
      "lazygit" = {
        source = ../../.config/lazygit;
        force = true;
      };
      "nvim" = {
        source = ../../.config/nvim;
        force = true;
      };
      "opencode" = {
        source = ../../.config/opencode;
        force = true;
      };
      "starship.toml".source = ../../.config/starship.toml;
      "yazi" = {
        source = ../../.config/yazi;
        force = true;
      };
    };
  };
}
