{ config, lib, pkgs, publicDotfilesDelivery, ... }:

let
  cfg = config.xj.publicDotfiles;
  # Cmd+digit selects a tmux window. Ghostty sends a private CSI sequence that
  # tmux claims as a user key, so no Alt/Meta chord is taken from shells or
  # editors. Cmd+1..8 pick that index; Cmd+9 and Cmd+0 pick the last window.
  windowSelectors = map (digit: {
    inherit digit;
    target = if digit >= 1 && digit <= 8 then toString digit else "\"{end}\"";
  }) (lib.range 0 9);
  selectorSequence = digit: "[90${toString digit}~";
  generatedTmuxWindowSelectors = lib.concatLines (
    [ "# Generated by Home Manager: Ghostty Cmd+digit window selectors." ]
    ++ map (s: ''set -s user-keys[${toString s.digit}] "\e${selectorSequence s.digit}"'') windowSelectors
    ++ map (s: "bind -n User${toString s.digit} select-window -t ${s.target}") windowSelectors
  );
  generatedGhosttyWindowSelectors = lib.concatLines (
    [ "# Generated by Home Manager: Cmd+digit sends tmux window-selector user keys." ]
    ++ lib.concatMap (s: map (key: "keybind = ${key}=text:\\x1b${selectorSequence s.digit}") [
      "super+digit_${toString s.digit}"
      "super+${toString s.digit}"
    ]) windowSelectors
  );
  # Pin tools to this generation, including bash for plugin env shebangs.
  tmuxServerPath = lib.makeBinPath [ pkgs.bash pkgs.tmux config.home.path ]
    + ":/opt/homebrew/bin:/opt/homebrew/sbin:${config.home.homeDirectory}/.orbstack/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
  fzfTmuxUrl = pkgs.tmuxPlugins.fzf-tmux-url.overrideAttrs (old: {
    postInstall = (old.postInstall or "") + ''
      substituteInPlace "$target/fzf-url.tmux" \
        --replace-fail 'echo "$extra_filter" > /tmp/filter' ""
    '';
  });
  easyjumpTmux = pkgs.tmuxPlugins.mkTmuxPlugin {
    pluginName = "easyjump";
    path = "easyjump.tmux";
    rtpFilePath = "easyjump.tmux";
    version = "unstable-2024-06-22";
    src = pkgs.fetchFromGitHub {
      owner = "roy2220";
      repo = "easyjump.tmux";
      rev = "538479e519698ed44f0cb432736b2274ce5a3e6c";
      hash = "sha256-rckm5DICFYkvfIIy8U3XOXDmGssX/r7npl7Pgpx/bdk=";
    };
    postInstall = ''
      substituteInPlace "$target/easyjump.tmux" \
        --replace-fail '#!/usr/bin/env python3' '#!${pkgs.python3}/bin/python3'
    '';
  };
in
{
  config = lib.mkIf cfg.enable {
    # HM's base config uses mkBefore (500), plugins use normal order (1000),
    # and extraConfig uses mkAfter (1500). PATH must precede plugin execution.
    xdg.configFile = {
      "tmux/tmux.conf".text = lib.mkOrder 499 ''
        set-environment -g PATH "${tmuxServerPath}"
      '';
      "tmux/user.conf" = publicDotfilesDelivery.mkRepoFile ".tmux.conf";
      "ghostty/user.conf" = publicDotfilesDelivery.mkRepoFile ".config/ghostty/config";
      "ghostty/window-selectors.generated.conf".text = generatedGhosttyWindowSelectors;
    };

    programs.tmux = {
      enable = true;
      package = null;
      baseIndex = 1;
      escapeTime = 0;
      historyLimit = 50000;
      keyMode = "vi";
      mouse = true;
      prefix = "C-s";
      terminal = "tmux-256color";
      plugins = [
        fzfTmuxUrl
        {
          plugin = easyjumpTmux;
          extraConfig = ''
            set -g @easyjump-key-binding "J"
          '';
        }
      ];
      extraConfig = ''
        source-file ${config.xdg.configHome}/tmux/user.conf
      '' + generatedTmuxWindowSelectors;
    };

    programs.ghostty = {
      enable = true;
      package = null;
      settings = {
        command = "${pkgs.tmux}/bin/tmux new-session -A -s main";
        "config-file" = [
          "${config.xdg.configHome}/ghostty/user.conf"
          "${config.xdg.configHome}/ghostty/window-selectors.generated.conf"
        ];
      };
    };
  };
}
