{ config, lib, pkgs, publicDotfilesDelivery, ... }:

let
  cfg = config.xj.publicDotfiles;
  legacySelectors = builtins.fromJSON (builtins.readFile ../../config/terminal/legacy-selectors.json);
  ghosttyLegacySelectorKeybinds = lib.concatMap (
    selector:
    map (shortcut: "${shortcut}=text:\\x1b${selector.tmuxKey}") selector.ghosttyKeybinds
  ) legacySelectors;
  generatedTmuxLegacySelectorBindings = lib.concatLines (
    [
      "# Generated from config/terminal/legacy-selectors.json."
      "# Keep Ghostty legacy selector bridges and tmux root selector bindings in sync there."
    ]
    ++ map (selector: "bind -n M-${selector.tmuxKey} ${selector.tmuxCommand}") legacySelectors
  );
  generatedGhosttyLegacySelectorBindings = lib.concatLines (
    [ "# Generated by Home Manager from config/terminal/legacy-selectors.json." ]
    ++ map (keybind: "keybind = ${keybind}") ghosttyLegacySelectorKeybinds
  );
  # Pin tools to this generation, including bash for plugin env shebangs.
  tmuxServerPath = lib.makeBinPath [ pkgs.bash pkgs.tmux config.home.path ]
    + ":/opt/homebrew/bin:/opt/homebrew/sbin:${config.home.homeDirectory}/.orbstack/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
  fzfTmuxUrl = pkgs.tmuxPlugins.fzf-tmux-url.overrideAttrs (old: {
    postInstall = (old.postInstall or "") + ''
      substituteInPlace "$target/fzf-url.tmux" \
        --replace-fail 'echo "$extra_filter" > /tmp/filter' ""
    '';
  });
  easyjumpTmux = pkgs.tmuxPlugins.mkTmuxPlugin {
    pluginName = "easyjump";
    path = "easyjump.tmux";
    rtpFilePath = "easyjump.tmux";
    version = "unstable-2024-06-22";
    src = pkgs.fetchFromGitHub {
      owner = "roy2220";
      repo = "easyjump.tmux";
      rev = "538479e519698ed44f0cb432736b2274ce5a3e6c";
      hash = "sha256-rckm5DICFYkvfIIy8U3XOXDmGssX/r7npl7Pgpx/bdk=";
    };
    postInstall = ''
      substituteInPlace "$target/easyjump.tmux" \
        --replace-fail '#!/usr/bin/env python3' '#!${pkgs.python3}/bin/python3'
    '';
  };
in
{
  config = lib.mkIf cfg.enable {
    # HM's base config uses mkBefore (500), plugins use normal order (1000),
    # and extraConfig uses mkAfter (1500). PATH must precede plugin execution.
    xdg.configFile = {
      "tmux/tmux.conf".text = lib.mkOrder 499 ''
        set-environment -g PATH "${tmuxServerPath}"
      '';
      "tmux/user.conf" = publicDotfilesDelivery.mkRepoFile ".tmux.conf";
      "ghostty/user.conf" = publicDotfilesDelivery.mkRepoFile ".config/ghostty/config";
      "ghostty/legacy-selectors.generated.conf".text = generatedGhosttyLegacySelectorBindings;
    };

    programs.tmux = {
      enable = true;
      package = null;
      baseIndex = 1;
      escapeTime = 0;
      historyLimit = 50000;
      keyMode = "vi";
      mouse = true;
      prefix = "C-s";
      terminal = "tmux-256color";
      plugins = [
        fzfTmuxUrl
        {
          plugin = easyjumpTmux;
          extraConfig = ''
            set -g @easyjump-key-binding "J"
          '';
        }
        pkgs.tmuxPlugins.session-wizard
        {
          plugin = pkgs.tmuxPlugins.tmux-fzf;
          extraConfig = ''
            TMUX_FZF_LAUNCH_KEY="F"
          '';
        }
      ];
      extraConfig = ''
        source-file ${config.xdg.configHome}/tmux/user.conf
      '' + generatedTmuxLegacySelectorBindings;
    };

    programs.ghostty = {
      enable = true;
      package = null;
      settings = {
        command = "${pkgs.tmux}/bin/tmux new-session -A -s main";
        "config-file" = [
          "${config.xdg.configHome}/ghostty/user.conf"
          "${config.xdg.configHome}/ghostty/legacy-selectors.generated.conf"
        ];
      };
    };
  };
}
