"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 2000
scan_timeout = 100
right_format = "$golang$time"

[character]
vimcmd_symbol = "[V](bold green) "
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[time]
disabled = false
format = "[$time]($style)"

[hostname]
ssh_only = true
ssh_symbol = " "
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

[line_break]
disabled = true

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[golang]
disabled = true

[git_status]
disabled = true

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
disabled = true

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
disabled = true

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
