#!/usr/bin/env python3
"""Focused doctor fixtures; no live home or activation."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
root = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("public_control", root / "scripts/public-control.py")
control = importlib.util.module_from_spec(spec)
spec.loader.exec_module(control)


with tempfile.TemporaryDirectory(prefix="tmux-options-test-") as tmp:
    config = Path(tmp) / ".tmux.conf"
    expected = {"pane-border-status": "top", "pane-border-format": " #P #{@agent_label} "}
    for command in ("set", "setw", "set-option", "set-window-option"):
        config.write_text('bind -N "description" \\\n  send-prefix\n\n'
                          f'{command} -g pane-border-status top\n'
                          'bind "unterminated\nset -g unrelated "unterminated\n'
                          f"{command} -g pane-border-format ' #P #{{@agent_label}} '\n")
        assert control.tmux_options(config) == expected
    config.write_text('bind "unterminated\nset -g unrelated value\n')
    assert control.tmux_options(config) == {}
print("tmux parser ignores unrelated multiline and malformed declarations")


def make_generation(path, content):
    files = path / "home-files/.config/example"
    files.parent.mkdir(parents=True)
    files.write_text(content)
    (path / "activate").write_text("activate-v1\n")


with tempfile.TemporaryDirectory(prefix="doctor-fingerprint-") as tmp:
    base = Path(tmp).resolve()
    repo, home, active, desired = [base / name for name in ("repo", "home", "active", "desired")]
    repo.mkdir()
    home.mkdir()
    make_generation(active, "same generated bytes\n")
    make_generation(desired, "same generated bytes\n")
    profile = home / ".local/state/nix/profiles/home-manager"
    profile.parent.mkdir(parents=True)
    profile.symlink_to(active)

    def runner(argv, **kwargs):
        argv = list(map(str, argv))
        if argv[0] == "git":
            output = "" if "status" in argv else "b" * 40
            return subprocess.CompletedProcess(argv, 0, output, "")
        return subprocess.CompletedProcess(argv, 1, "", "")

    app = control.Control(repo, home, generation=desired, runner=runner)
    report = app.doctor()
    assert report["source"]["revision"] == "b" * 40
    assert report["active_matches_desired"] is True
    assert report["active_output_fingerprint"] == report["desired_output_fingerprint"]
    assert "active_source_matches_checkout" not in report
    (desired / "home-files/.config/example").write_text("changed generated bytes\n")
    assert app.doctor()["active_matches_desired"] is False
print("doctor compares generated home-files and activation content, not Git revision")


with tempfile.TemporaryDirectory(prefix="doctor-integrations-") as tmp:
    home = Path(tmp)
    marker = "sensitive-fixture-command-do-not-print"
    live = home / ".claude/settings.json"
    live.parent.mkdir()
    live.write_text(json.dumps({"hooks": {"Stop": [{"hooks": [{"type": "command", "command": marker}]}]},
                                "statusLine": {"type": "command", "command": marker, "refreshInterval": 5}}))
    codex = home / ".codex/hooks.json"
    codex.parent.mkdir()
    codex.write_text("{}")
    plan = control.integration_plan(home, root)
    output = json.dumps(plan)
    assert marker not in output
    assert plan["claude"]["merge_plan"] and plan["codex"]["merge_plan"]
print("doctor integration plans remain sanitized")


with tempfile.TemporaryDirectory(prefix="detach-agent-config-") as tmp:
    home = Path(tmp) / "home"
    repo = (Path(tmp) / "repo").resolve()
    source = repo / "config/codex/hooks.json"
    source.parent.mkdir(parents=True)
    source.write_text('{"preserve":true}\n')
    live = home / ".codex/hooks.json"
    live.parent.mkdir(parents=True)
    live.symlink_to(source)
    before = live.read_bytes()
    assert control.detach_mutable(home, repo, apply=False)[0]["action"] == "detach-managed-link-preserve-bytes"
    control.detach_mutable(home, repo, apply=True)
    assert live.is_file() and not live.is_symlink() and live.read_bytes() == before
    assert source.read_bytes() == before and live.stat().st_mode & 0o777 == 0o600
print("activation helper preserves mutable managed-link bytes")


# Package lookup must detect PATH drift without exposing native stdout or paths.
from unittest.mock import patch
with tempfile.TemporaryDirectory(prefix="doctor-programs-") as tmp:
    base = Path(tmp)
    repo, home, generation = [base / name for name in ("repo", "home", "generation")]
    repo.mkdir(); home.mkdir()
    make_generation(generation, "config")
    owned = generation / "home-files/.config/public-dotfiles/generation.json"
    owned.parent.mkdir(parents=True)
    owned.write_text(json.dumps({"owned_programs": {
        "yazi": {"owner": "nix", "version": "26.9.1"},
        "ya": {"owner": "nix", "version": "26.9.1"},
    }}))
    binaries = generation / "home-path/bin"
    binaries.mkdir(parents=True)
    for name in ("yazi", "ya"):
        (binaries / name).write_text("fixture")
    foreign = base / "sensitive-fixture-binary"
    foreign.write_text("fixture")
    marker = "private-native-output-do-not-print"

    def runner(argv, **kwargs):
        text = "" if "status" in argv else "b" * 40 if str(argv[0]) == "git" else "Yazi 26.9.1 " + marker
        return subprocess.CompletedProcess(argv, 0, text, "")

    app = control.Control(repo, home, generation=generation, runner=runner)
    with patch.object(control.shutil, "which", side_effect=lambda name: str(binaries / name)):
        report = app.programs()
        assert all(item["matches_generation"] is True for item in report["commands"].values())
        assert report["paired_runtime_versions_match"] is True
    with patch.object(control.shutil, "which", return_value=str(foreign)):
        report = app.programs()
        assert all(item["matches_generation"] is False for item in report["commands"].values())
        assert marker not in json.dumps(report) and str(base) not in json.dumps(report)
    with patch.object(control.shutil, "which", return_value=None):
        report = app.programs()
        assert report["paired_runtime_versions_match"] is None
        assert all(item["matches_generation"] is None for item in report["commands"].values())
print("paired CLI drift, missing state and private-output suppression verified")


with tempfile.TemporaryDirectory(prefix="native-plan-") as tmp:
    base = Path(tmp)
    repo, home, generation = [base / name for name in ("repo", "home", "generation")]
    repo.mkdir(); home.mkdir()
    make_generation(generation, "new bytes")
    yazi = generation / "home-files/.config/yazi/yazi.toml"
    yazi.parent.mkdir(); yazi.write_text("new config")
    live = home / ".config/yazi/yazi.toml"
    live.parent.mkdir(parents=True); live.write_text("old config")
    calls = []

    def runner(argv, **kwargs):
        calls.append(list(map(str, argv)))
        return subprocess.CompletedProcess(argv, 0, "" if "status" in argv else "c" * 40, "")

    app = control.Control(repo, home, generation=generation, runner=runner)
    with patch.object(control.shutil, "which", return_value=None):
        report = app.plan("home", "committed-head")
    assert "Restart Yazi" in report["after_apply"]
    assert report["files"]["changed"] == 1 and report["files"]["new"] == 1
    assert live.read_text() == "old config"
    assert all(call[0] == "git" for call in calls), "planning must not build or activate"
    assert report["apply_command"] == "task -g dotfiles:apply"
print("plan describes built file changes and reloads without activating or changing live state")


for options, message in (
    (("--plan", "--apply"), "cannot be combined"),
    (("--plan", "--skip-build"), "requires a built generation"),
):
    rejected = subprocess.run([str(root / "scripts/bootstrap-macos.sh"), *options], capture_output=True, text=True)
    assert rejected.returncode != 0 and message in rejected.stderr
print("standalone plan rejects activation, installation and incomplete-build flags")


if len(sys.argv) > 1:
    generation = Path(sys.argv[1])
    text = (generation / "home-files/Taskfile.yml").read_text()
    includes = [json.loads(line.split(":", 1)[1].strip()) for line in text.splitlines()
                if line.strip().startswith("taskfile:")]
    public_root = str(Path(includes[0]).parent.parent)
    with tempfile.TemporaryDirectory(prefix="global-operator-shim-") as tmp:
        # The standalone example targets an imaginary home; remap its declared
        # repository for this invocation, without changing the generated file.
        path = Path(tmp) / "Taskfile.yml"
        path.write_text(text.replace(public_root, str(root)))
        task = generation / "home-path/bin/task"
        listed = subprocess.run([str(task), "--taskfile", str(path), "--list-all"],
                                cwd=tmp, capture_output=True, text=True)
        assert listed.returncode == 0, listed.stderr
        assert "dotfiles:plan" in listed.stdout and "dotfiles:apply" in listed.stdout
        assert "new-human-req-doc" in listed.stdout
    print("generated global Task shim preserves common tasks and routes owning operations")
