#!/usr/bin/env python3
"""Focused doctor fixtures; no live home or activation."""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
root = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("public_control", root / "scripts/public-control.py")
control = importlib.util.module_from_spec(spec)
spec.loader.exec_module(control)


with tempfile.TemporaryDirectory(prefix="tmux-options-test-") as tmp:
    config = Path(tmp) / ".tmux.conf"
    expected = {"pane-border-status": "top", "pane-border-format": " #P #{@agent_label} "}
    for command in ("set", "setw", "set-option", "set-window-option"):
        config.write_text('bind -N "description" \\\n  send-prefix\n\n'
                          f'{command} -g pane-border-status top\n'
                          'bind "unterminated\nset -g unrelated "unterminated\n'
                          f"{command} -g pane-border-format ' #P #{{@agent_label}} '\n")
        assert control.tmux_options(config) == expected
    config.write_text('bind "unterminated\nset -g unrelated value\n')
    assert control.tmux_options(config) == {}
print("tmux parser ignores unrelated multiline and malformed declarations")

# The public Brewfile is a baseline every Mac installs; personal additions live
# in a downstream overlay ledger. Every entry must say why the baseline needs it.
for number, line in enumerate((root / "Brewfile").read_text().splitlines(), 1):
    entry = line.strip()
    assert not entry.startswith(("tap ", "mas ")), f"Brewfile:{number}: taps and App Store apps belong in an overlay Brewfile"
    if entry.startswith(("brew ", "cask ")):
        assert any(f"# {reason}: " in entry for reason in ("needs", "baseline")), f"Brewfile:{number}: add '# needs: <public consumer>' or '# baseline: <role>'"
print("public Brewfile entries are justified baseline packages")


def make_generation(path, content):
    files = path / "home-files/.config/example"
    files.parent.mkdir(parents=True)
    files.write_text(content)
    (path / "activate").write_text("activate-v1\n")


with tempfile.TemporaryDirectory(prefix="doctor-fingerprint-") as tmp:
    base = Path(tmp).resolve()
    repo, home, active, desired = [base / name for name in ("repo", "home", "active", "desired")]
    repo.mkdir()
    home.mkdir()
    make_generation(active, "same generated bytes\n")
    make_generation(desired, "same generated bytes\n")
    profile = home / ".local/state/nix/profiles/home-manager"
    profile.parent.mkdir(parents=True)
    profile.symlink_to(active)

    def runner(argv, **kwargs):
        argv = list(map(str, argv))
        if argv[0] == "git":
            output = "" if "status" in argv else "b" * 40
            return subprocess.CompletedProcess(argv, 0, output, "")
        return subprocess.CompletedProcess(argv, 1, "", "")

    app = control.Control(repo, home, generation=desired, runner=runner)
    report = app.doctor()
    assert report["source"]["revision"] == "b" * 40
    assert report["active_matches_desired"] is True
    assert report["active_output_fingerprint"] == report["desired_output_fingerprint"]
    assert "active_source_matches_checkout" not in report
    (desired / "home-files/.config/example").write_text("changed generated bytes\n")
    assert app.doctor()["active_matches_desired"] is False
print("doctor compares generated home-files and activation content, not Git revision")


if len(sys.argv) > 1:  # jq comes from the generation; a fresh Mac may have none yet
    os.environ["PATH"] = str(Path(sys.argv[1]) / "home-path/bin") + os.pathsep + os.environ["PATH"]
with tempfile.TemporaryDirectory(prefix="doctor-settings-merge-") as tmp:
    home = Path(tmp)
    marker = "sensitive-fixture-command-do-not-print"
    live = home / ".claude/settings.json"
    live.parent.mkdir()
    live.write_text(json.dumps({"hooks": {"Stop": [{"hooks": [{"type": "command", "command": marker}]}]}, "runtimeOnly": marker}))
    codex = home / ".codex/hooks.json"
    codex.parent.mkdir()
    codex.write_text((root / "config/codex/hooks.json").read_text())
    report = control.settings_merge(home, root)
    assert marker not in json.dumps(report)
    claude = report[".claude/settings.json"]
    assert claude["state"] == "apply-would-update" and "hooks" in claude["keys"] and "runtimeOnly" not in claude["keys"]
    assert report[".codex/hooks.json"] == {"state": "in-sync", "keys": []}
    assert control.settings_merge(home, root, targets=()) == {}
print("doctor reports pending settings merges by key name only")


with tempfile.TemporaryDirectory(prefix="doctor-upstream-") as tmp:
    repo, overlay = Path(tmp) / "repo", Path(tmp) / "overlay"
    (repo / ".upstream").mkdir(parents=True)
    (repo / ".upstream/2026-10-08-kept.md").write_text("pending\n")
    overlay.mkdir()
    (overlay / "host.nix").write_text("# upstream-pending: 2026-10-08-kept\n# upstream-pending: 2026-09-01-landed\n")
    (overlay / "ignored.nix").write_text("# upstream-pending: untracked-only\n")
    subprocess.run(["git", "init", "-q", str(overlay)], check=True)
    subprocess.run(["git", "-C", str(overlay), "add", "host.nix"], check=True)
    assert control.upstream_proposals(repo, overlay) == {"pending": ["2026-10-08-kept"], "stale_overlay_markers": ["2026-09-01-landed"]}
    assert control.upstream_proposals(repo) == {"pending": ["2026-10-08-kept"], "stale_overlay_markers": []}
print("doctor counts upstream proposals and flags overlay markers whose proposal is gone")


with tempfile.TemporaryDirectory(prefix="detach-agent-config-") as tmp:
    home = Path(tmp) / "home"
    repo = (Path(tmp) / "repo").resolve()
    source = repo / "config/codex/hooks.json"
    source.parent.mkdir(parents=True)
    source.write_text('{"preserve":true}\n')
    live = home / ".codex/hooks.json"
    live.parent.mkdir(parents=True)
    live.symlink_to(source)
    before = live.read_bytes()
    assert control.detach_mutable(home, repo, apply=False)[0]["action"] == "detach-managed-link-preserve-bytes"
    control.detach_mutable(home, repo, apply=True)
    assert live.is_file() and not live.is_symlink() and live.read_bytes() == before
    assert source.read_bytes() == before and live.stat().st_mode & 0o777 == 0o600
print("activation helper preserves mutable managed-link bytes")


# Package lookup must detect PATH drift without exposing native stdout or paths.
from unittest.mock import patch
with tempfile.TemporaryDirectory(prefix="doctor-programs-") as tmp:
    base = Path(tmp)
    repo, home, generation = [base / name for name in ("repo", "home", "generation")]
    repo.mkdir(); home.mkdir()
    make_generation(generation, "config")
    owned = generation / "home-files/.config/public-dotfiles/generation.json"
    owned.parent.mkdir(parents=True)
    owned.write_text(json.dumps({"owned_programs": {
        "yazi": {"owner": "nix", "version": "26.9.1"},
        "ya": {"owner": "nix", "version": "26.9.1"},
    }}))
    binaries = generation / "home-path/bin"
    binaries.mkdir(parents=True)
    for name in ("yazi", "ya"):
        (binaries / name).write_text("fixture")
    foreign = base / "sensitive-fixture-binary"
    foreign.write_text("fixture")
    marker = "private-native-output-do-not-print"

    def runner(argv, **kwargs):
        text = "" if "status" in argv else "b" * 40 if str(argv[0]) == "git" else "Yazi 26.9.1 " + marker
        return subprocess.CompletedProcess(argv, 0, text, "")

    app = control.Control(repo, home, generation=generation, runner=runner)
    with patch.object(control.shutil, "which", side_effect=lambda name: str(binaries / name)):
        report = app.programs()
        assert all(item["matches_generation"] is True for item in report["commands"].values())
        assert report["paired_runtime_versions_match"] is True
    with patch.object(control.shutil, "which", return_value=str(foreign)):
        report = app.programs()
        assert all(item["matches_generation"] is False for item in report["commands"].values())
        assert marker not in json.dumps(report) and str(base) not in json.dumps(report)
    with patch.object(control.shutil, "which", return_value=None):
        report = app.programs()
        assert report["paired_runtime_versions_match"] is None
        assert all(item["matches_generation"] is None for item in report["commands"].values())
print("paired CLI drift, missing state and private-output suppression verified")


with tempfile.TemporaryDirectory(prefix="native-plan-") as tmp:
    base = Path(tmp)
    repo, home, generation = [base / name for name in ("repo", "home", "generation")]
    repo.mkdir(); home.mkdir()
    make_generation(generation, "new bytes")
    yazi = generation / "home-files/.config/yazi/yazi.toml"
    yazi.parent.mkdir(); yazi.write_text("new config")
    live = home / ".config/yazi/yazi.toml"
    live.parent.mkdir(parents=True); live.write_text("old config")
    calls = []

    def runner(argv, **kwargs):
        calls.append(list(map(str, argv)))
        return subprocess.CompletedProcess(argv, 0, "" if "status" in argv else "c" * 40, "")

    app = control.Control(repo, home, generation=generation, runner=runner)
    with patch.object(control.shutil, "which", return_value=None):
        report = app.plan("home", "committed-head")
    assert "Restart Yazi" in report["after_apply"]
    assert report["files"]["changed"] == 1 and report["files"]["new"] == 1
    assert live.read_text() == "old config"
    assert all(call[0] == "git" for call in calls), "planning must not build or activate"
    assert report["apply_command"] == "task -g dotfiles:apply"
print("plan describes built file changes and reloads without activating or changing live state")

with patch.object(control.Control, "select", side_effect=AssertionError("must reject before probing")):
    with patch.object(sys, "argv", ["public-control.py", "plan", "--generation", "/nonexistent", "--scope", "system"]):
        try:
            control.main()
        except SystemExit as error:
            assert error.code == 2
        else:
            raise AssertionError("obsolete system scope must be rejected")
try:
    app.plan("system")
except control.SafeError as error:
    assert "home-scope-only" in str(error)
else:
    raise AssertionError("internal callers must not describe unsupported system activation")
print("obsolete system planning is rejected before inspecting live state")


for options, message in (
    (("--plan", "--apply"), "choose one operation"),
    ((), "choose --plan, --apply, or --rollback"),
):
    rejected = subprocess.run([str(root / "scripts/bootstrap-macos.sh"), *options], capture_output=True, text=True)
    assert rejected.returncode != 0 and message in rejected.stderr
print("standalone operator requires exactly one explicit operation")


# Run the actual bootstrap main under macOS Bash 3.2 with all external effects
# stubbed. Its command substitution must propagate each generation failure.
with tempfile.TemporaryDirectory(prefix="bootstrap-failure-") as tmp:
    fixture = Path(tmp)
    source = (root / "scripts/bootstrap-macos.sh").read_text().rsplit('main "$@"', 1)[0]
    driver = fixture / "driver.sh"
    driver.write_text(source + r'''
bootstrap_root="$1"
target_user=fixture
preflight() { host_platform=aarch64-darwin; }
ensure_nix() { :; }
guard_private_overlay_apply() { :; }
build_activation() { printf built >"$bootstrap_root/built"; }
apply_home_manager() { :; }
case "$2" in
  mkdir|mktemp|cat|mv) eval "$2() { return 41; }" ;;
esac
main --apply
''')
    for fault in ("mkdir", "mktemp", "cat", "mv", "ok"):
        directory = fixture / fault
        (directory / "fixture").mkdir(parents=True)
        old = directory / "fixture/flake.nix"
        old.write_text("old flake")
        result = subprocess.run(["/bin/bash", str(driver), str(directory), fault], capture_output=True, text=True)
        assert (result.returncode == 0) == (fault == "ok"), result.stderr
        assert (directory / "built").exists() == (fault == "ok")
        if fault != "ok":
            assert old.read_text() == "old flake"
            assert "generated local" not in result.stderr
        assert not list(old.parent.glob(".flake.nix.*"))
    escaped = subprocess.run(["/bin/bash", "-c", source + '\nnix_string "$1"', "fixture", "${builtins.toString 42}"],
                             capture_output=True, text=True, check=True)
    assert escaped.stdout == '"\\${builtins.toString 42}"', repr(escaped.stdout)
print("bootstrap generation fails closed and quotes literal Nix interpolation")


if len(sys.argv) > 1:
    generation = Path(sys.argv[1])
    text = (generation / "home-files/Taskfile.yml").read_text()
    includes = [json.loads(line.split(":", 1)[1].strip()) for line in text.splitlines()
                if line.strip().startswith("taskfile:")]
    public_root = str(Path(includes[0]).parent.parent)
    with tempfile.TemporaryDirectory(prefix="global-operator-shim-") as tmp:
        # The standalone example targets an imaginary home; remap its declared
        # repository for this invocation, without changing the generated file.
        path = Path(tmp) / "Taskfile.yml"
        path.write_text(text.replace(public_root, str(root)))
        task = generation / "home-path/bin/task"
        listed = subprocess.run([str(task), "--taskfile", str(path), "--list-all"],
                                cwd=tmp, capture_output=True, text=True)
        assert listed.returncode == 0, listed.stderr
        assert "dotfiles:plan" in listed.stdout and "dotfiles:apply" in listed.stdout
        assert "new-human-req-doc" in listed.stdout
    print("generated global Task shim preserves common tasks and routes owning operations")
    with tempfile.TemporaryDirectory(prefix="generated-toml-parser-") as tmp:
        fixture = Path(tmp)
        (fixture / "home-files").mkdir()
        for source in (generation / "home-files").iterdir():
            (fixture / "home-files" / source.name).symlink_to(source)
        (fixture / "home-path").symlink_to((generation / "home-path").resolve())
        toml = fixture / "home-files/fixture.toml"
        for text, valid in (("[fixture]\nvalue = 1\n", True), ("[broken\n", False)):
            toml.write_text(text)
            checked = subprocess.run([sys.executable, str(root / "scripts/verify-generated-links.py"), str(fixture),
                                      "--map", public_root + "=" + str(root)], capture_output=True, text=True)
            assert (checked.returncode == 0) == valid, checked.stderr
    print("native generated-config gate accepts valid TOML and rejects malformed TOML")
    with tempfile.TemporaryDirectory(prefix="generated-live-ownership-") as tmp:
        fixture, checkout = Path(tmp) / "generation", Path(tmp) / "checkout"
        (fixture / "home-files").mkdir(parents=True)
        for source in (generation / "home-files").iterdir():
            (fixture / "home-files" / source.name).symlink_to(source)
        (fixture / "home-path").symlink_to((generation / "home-path").resolve())
        declared = "/Users/example/fixture-checkout"
        (fixture / "home-files/fixture-live").symlink_to(declared + "/.config/fixture-live")
        live = checkout / ".config/fixture-live"
        (live / "runtime/plugin/tests").mkdir(parents=True)
        (live / "runtime/plugin/tests/all.json").write_text('{"bad": "\t\n"}')
        (checkout / ".gitignore").write_text("/.config/fixture-live/runtime/\n")
        tracked = live / "settings.json"
        tracked.write_text("{}")
        subprocess.run(["git", "init", "-q", str(checkout)], check=True)
        subprocess.run(["git", "-C", str(checkout), "add", "."], check=True)

        def verify(*extra):
            return subprocess.run([sys.executable, str(root / "scripts/verify-generated-links.py"), str(fixture),
                                   "--map", declared + "=" + str(checkout), "--map", public_root + "=" + str(root), *extra],
                                  capture_output=True, text=True)
        checked = verify()
        assert checked.returncode == 0, checked.stderr
        tracked.write_text("{broken")
        assert verify().returncode != 0, "tracked invalid live config must fail"
        tracked.write_text("{}")
        (live / "new.json").write_text("{broken")
        assert verify().returncode != 0, "untracked unignored live config must fail"
        (live / "new.json").unlink()
        subprocess.run(["/bin/mv", str(checkout / ".git"), str(Path(tmp) / "git")], check=True)
        assert "neither a Git checkout nor store source" in verify().stderr, "non-Git live trees must fail closed"
        subprocess.run(["/bin/mv", str(Path(tmp) / "git"), str(checkout / ".git")], check=True)
        (fixture / "home-files/.claude").unlink(missing_ok=True)
        (fixture / "home-files/.claude").mkdir(exist_ok=True)
        (fixture / "home-files/.claude/settings.json").write_text("{}")
        assert "mutable target is owned by home.file" in verify().stderr
        (fixture / "home-files/.claude/settings.json").unlink()
        (fixture / "home-files/dangling").symlink_to(declared + "/missing")
        assert "dangling generated target" in verify().stderr
    print("live-link parser gate skips Git-ignored runtime trees and rejects owned invalid config")
