#!/usr/bin/env python3
"""Focused doctor fixtures; no live home or activation."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
root = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("public_control", root / "scripts/public-control.py")
control = importlib.util.module_from_spec(spec)
spec.loader.exec_module(control)


with tempfile.TemporaryDirectory(prefix="tmux-options-test-") as tmp:
    config = Path(tmp) / ".tmux.conf"
    expected = {"pane-border-status": "top", "pane-border-format": " #P #{@agent_label} "}
    for command in ("set", "setw", "set-option", "set-window-option"):
        config.write_text('bind -N "description" \\\n  send-prefix\n\n'
                          f'{command} -g pane-border-status top\n'
                          'bind "unterminated\nset -g unrelated "unterminated\n'
                          f"{command} -g pane-border-format ' #P #{{@agent_label}} '\n")
        assert control.tmux_options(config) == expected
    config.write_text('bind "unterminated\nset -g unrelated value\n')
    assert control.tmux_options(config) == {}
print("tmux parser ignores unrelated multiline and malformed declarations")


def make_generation(path, content):
    files = path / "home-files/.config/example"
    files.parent.mkdir(parents=True)
    files.write_text(content)
    (path / "activate").write_text("activate-v1\n")


with tempfile.TemporaryDirectory(prefix="doctor-fingerprint-") as tmp:
    base = Path(tmp).resolve()
    repo, home, active, desired = [base / name for name in ("repo", "home", "active", "desired")]
    repo.mkdir()
    home.mkdir()
    make_generation(active, "same generated bytes\n")
    make_generation(desired, "same generated bytes\n")
    profile = home / ".local/state/nix/profiles/home-manager"
    profile.parent.mkdir(parents=True)
    profile.symlink_to(active)

    def runner(argv, **kwargs):
        argv = list(map(str, argv))
        if argv[0] == "git":
            output = "" if "status" in argv else "b" * 40
            return subprocess.CompletedProcess(argv, 0, output, "")
        return subprocess.CompletedProcess(argv, 1, "", "")

    app = control.Control(repo, home, generation=desired, runner=runner)
    report = app.doctor()
    assert report["source"]["revision"] == "b" * 40
    assert report["active_matches_desired"] is True
    assert report["active_output_fingerprint"] == report["desired_output_fingerprint"]
    assert "active_source_matches_checkout" not in report
    (desired / "home-files/.config/example").write_text("changed generated bytes\n")
    assert app.doctor()["active_matches_desired"] is False
print("doctor compares generated home-files and activation content, not Git revision")


with tempfile.TemporaryDirectory(prefix="doctor-integrations-") as tmp:
    home = Path(tmp)
    marker = "sensitive-fixture-command-do-not-print"
    live = home / ".claude/settings.json"
    live.parent.mkdir()
    live.write_text(json.dumps({"hooks": {"Stop": [{"hooks": [{"type": "command", "command": marker}]}]},
                                "statusLine": {"type": "command", "command": marker, "refreshInterval": 5}}))
    codex = home / ".codex/hooks.json"
    codex.parent.mkdir()
    codex.write_text("{}")
    plan = control.integration_plan(home, root)
    output = json.dumps(plan)
    assert marker not in output
    assert plan["claude"]["merge_plan"] and plan["codex"]["merge_plan"]
print("doctor integration plans remain sanitized")


with tempfile.TemporaryDirectory(prefix="detach-agent-config-") as tmp:
    home = Path(tmp) / "home"
    repo = (Path(tmp) / "repo").resolve()
    source = repo / "config/codex/hooks.json"
    source.parent.mkdir(parents=True)
    source.write_text('{"preserve":true}\n')
    live = home / ".codex/hooks.json"
    live.parent.mkdir(parents=True)
    live.symlink_to(source)
    before = live.read_bytes()
    assert control.detach_mutable(home, repo, apply=False)[0]["action"] == "detach-managed-link-preserve-bytes"
    control.detach_mutable(home, repo, apply=True)
    assert live.is_file() and not live.is_symlink() and live.read_bytes() == before
    assert source.read_bytes() == before and live.stat().st_mode & 0o777 == 0o600
print("activation helper preserves mutable managed-link bytes")
