pkgs: [
  pkgs.atuin
  pkgs.bat
  pkgs.coreutils
  pkgs.eza
  pkgs.fd
  pkgs.fzf
  pkgs.git
  pkgs."git-lfs"
  pkgs.jq
  pkgs.ripgrep
  pkgs.starship
  pkgs.tealdeer
  pkgs.yazi
  pkgs.yq
  pkgs.zoxide
  pkgs.zsh
  pkgs."zsh-autopair"
  pkgs."zsh-autosuggestions"
  pkgs."zsh-fzf-tab"
  pkgs."zsh-syntax-highlighting"
  pkgs."zsh-vi-mode"
]
